backend:
  name: github
  repo: toolrar/blog
  branch: main

media_folder: "blog/text-tools/img"
public_folder: "/blog/text-tools/img"

collections:
  - name: "blog"
    label: "المدونة"
    folder: "blog/text-tools"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "صورة المقال", name: "image", widget: "image"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
